# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CLEAN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#  target 'CLEAN' do	
	pod 'FSCalendar'
#  end

  # Pods for CLEAN

  target 'CLEANTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CLEANUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
